#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="rails"

check_container_initialized
liftoff

export DISCOURSE_PORT_NUMBER=${LISTEN_PORT}
export DISCOURSE_SITE_NAME=SITE_TITLE=${SITE_TITLE}
export DISCOURSE_USERNAME=${ADMIN_USER}
export DISCOURSE_PASSWORD=${ADMIN_PASS}
export DISCOURSE_EMAIL=${ADMIN_EMAIL}
export DISCOURSE_FIRST_NAME=${ADMIN_FIRST_NAME}
export DISCOURSE_LAST_NAME=${ADMIN_LAST_NAME}

cd /app/
print_start "Starting Rails - Discourse version ${DISCOURSE_VERSION}"
silent exec bundle exec rails server -b 0.0.0.0
