
services:
  discourse-app:
    container_name: discourse-app
    image: tiredofit/discourse:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.discourse-example-com.rule=Host(`discourse.example.com`)
      - traefik.http.services.discourse-example-com.loadbalancer.server.port=3000
    volumes:
      - ./logs:/data/logs
      - ./data/uploads:/data/uploads
      - ./data/backups:/data/backups
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-app

      - DB_HOST=discourse-db
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password

      - REDIS_HOST=discourse-redis


      - ADMIN_EMAIL=admin@example.com
      - ADMIN_NAME=Admin User
      - ADMIN_USER=admin
      - ADMIN_PASS=min10charpass

      - SITE_HOSTNAME=discourse.example.com
      - DELIVER_SECURE_ASSETS=TRUE

      - SMTP_PORT=25
      - SMTP_FROM=noreply@example.com
      - SMTP_TLS=false
      - SMTP_DISABLE_STARTTLS=true
      - SMTP_PORT=25
      - SMTP_HOST=postfix-relay

      - DEVELOPER_EMAILS=hostmaster@example.com
    restart: always
    networks:
      - proxy
      - services

  discourse-db:
    container_name: discourse-db
    image: tiredofit/postgres:17
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-db

      - SUPERUSER_PASS=superuser
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password
    networks:
      - services

  discourse-redis:
    image: tiredofit/redis:7
    container_name: discourse-redis
    #volumes:
    #  - ./redis:/var/lib/redis
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-redis
    networks:
      - services
    restart: always

  discourse-db-backup:
    image: tiredofit/db-backup
    container_name: discourse-db-backup
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-db-backup
      - DB01_HOST=discourse-db
      - DB01_TYPE=postgres
      - DB01_NAME=discourse
      - DB01_USER=discourse
      - DB01_PASS=password
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - services
    restart: always


networks:
  proxy:
    external: true
  services:
    external: true

