#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="rails"

check_container_initialized
liftoff

export DISCOURSE_SITE_TITLE=${SITE_TITLE}
export UNICORN_WORKERS=${UNICORN_WORKERS}

cd /app/
print_start "Starting Unicorn - Discourse version ${DISCOURSE_VERSION}"
sudo -u discourse \
                    exec bin/unicorn \
                                    -E production \
                                    -o 0.0.0.0 \
                                    -p "${LISTEN_PORT}" \
                                    -c "config/unicorn.conf.rb"


