#!/usr/bin/with-contenv bash


if [ ! -f /tmp/state/20-sidekiq ]; then
sleep 2

    cd /app/

    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-sidekiq
fi

cd /app/
echo ''
echo '** Starting Sidekiq..'
exec bundle exec sidekiq -e production > log/sidekiq.log

